[package]
name = "conways"
version = "0.1.0"
authors = ["Taylor Thurlow <taylorthurlow8@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6.4"
piston = "0.39.0"
piston2d-graphics = "0.28.0"
piston2d-opengl_graphics = "0.57.0"
piston_window = "0.81.0"
pistoncore-glutin_window = "0.51.0"
